### ISSUE TITLE
Doesn't work on Android 14

### ISSUE THREAD

**Issue by dariusz-goc** [Xposed-Modules-Repo/moe.henry_zhr.kill_domain_verification#1]
After upgrading to Android 14 the module no longer works. Android exhibits default behavior, automatically verifying official apps while preventing others from opening links.

Pls fix.

**Comment by Lanchon** [comment]
@dariusz-goc please close this duplicate issue. thanks!

https://github.com/Henry-ZHR/KillDomainVerification/issues/5
